services:
  # Web service
  - type: web
    runtime: docker
    name: roastgithub-api
    plan: free
    branch: main
    autoDeploy: true
    dockerfilePath: Dockerfile
    envVars:
      - key: STAGE_STATUS
        value: "prod"
      - key: APP_NAME
        value: "roastgithub-api"
      - key: APP_HOST
        value: "0.0.0.0"
      - key: APP_PORT
        value: "3000"
      - key: GEMINI_API_KEY
        value: "YOUR_API_KEY"
      - key: GITHUB_TOKEN
        value: "YOUR_GITHUB_TOKEN"
      - key: REDIS_HOST
        fromService:
          name: roastgithub-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: roastgithub-redis
          type: redis
          property: port
      - key: REDIS_PASSWORD
        value: "" # Coz use internal redis
      - key: REDIS_DB_NUMBER
        value: "0"
  # Redis service
  - type: redis
    name: roastgithub-redis
    plan: free
    ipAllowList: [] # Internal redis

